### ISSUE TITLE
Using pydub for audio loading

### ISSUE THREAD

**Issue by suquark** [Meowtrix/osu-amt-beatmap-generator#1]
Currently it seems that we use `BASS` lib for audio reading. It only supports 44.1K and may not exist in certain platforms.

If we make use of `pydub` pkg (which depends on ffmpeg or libav), we can support most audio formats and it can work under linux/*nix systems.

@Blealtan

**Comment by Blealtan** [comment]
No, `BASS` not only supports 44.1kHz mp3, and it exists on Windows 32bit/64bit, Linux 32bit/64bit and Mac.

The limitation on audio format and sample frequency is due to osu! standard behavior, which says 44.1kHz mp3 is recommended; thus I assume this to happen for easier audio preprocess.

Also, usually different decoders generate raw samples with different time offset, which may lead to audio and beatmap misaligning if we use `pydub` while original osu! uses `BASS`.
